/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mingspy_jseg_JSegJNI */

#ifndef _Included_com_mingspy_jseg_JSegJNI
#define _Included_com_mingspy_jseg_JSegJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    SetDictFolder
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mingspy_jseg_JSegJNI_SetDictFolder
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    MaxSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_jseg_JSegJNI_MaxSplit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    FullSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_jseg_JSegJNI_FullSplit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    OneGramSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_jseg_JSegJNI_OneGramSplit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    Test
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mingspy_jseg_JSegJNI_Test
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
