/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mingspy_jseg_JSegJNI */

#ifndef _Included_com_mingspy_jseg_JSegJNI
#define _Included_com_mingspy_jseg_JSegJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    MaxSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_jseg_JSegJNI_MaxSplit
(JNIEnv *, jclass, jstring);

/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    FullSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_jseg_JSegJNI_FullSplit
(JNIEnv *, jclass, jstring);

/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    UniGramSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_jseg_JSegJNI_UniGramSplit
(JNIEnv *, jclass, jstring);

/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    BiGramSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_jseg_JSegJNI_BiGramSplit
(JNIEnv *, jclass, jstring);

/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    MixSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_jseg_JSegJNI_MixSplit
(JNIEnv *, jclass, jstring);

/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    Test
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mingspy_jseg_JSegJNI_Test
(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
